import type { Event } from '@/types/database';

export const mockEvents: Event[] = [
  {
    "id": "evt-001",
    "title": "Fall Welcome Mixer",
    "description": "Meet fellow students and kick off the semester with free food, games, and networking.",
    "club_id": null,
    "location": "Student Union Ballroom",
    "start_time": "2024-08-26T17:00:00Z",
    "end_time": "2024-08-26T20:00:00Z",
    "tags": [
      "social",
      "networking",
      "welcome"
    ],
    "category": "Social",
    "max_attendees": 200,
    "rsvp_count": 145,
    "organizer_id": null,
    "image_url": null,
    "is_virtual": false,
    "virtual_link": null,
    "created_at": "2024-07-15T00:00:00Z"
  },
  {
    "id": "evt-002",
    "title": "AI Workshop: Intro to LLMs",
    "description": "Hands-on workshop covering Large Language Models, prompt engineering, and building AI applications.",
    "club_id": "club-001",
    "location": "MacQuarrie Hall 225",
    "start_time": "2024-09-05T17:00:00Z",
    "end_time": "2024-09-05T19:00:00Z",
    "tags": [
      "AI",
      "workshop",
      "machine learning",
      "LLM"
    ],
    "category": "Workshop",
    "max_attendees": 50,
    "rsvp_count": 48,
    "organizer_id": null,
    "image_url": null,
    "is_virtual": false,
    "virtual_link": null,
    "created_at": "2024-07-15T00:00:00Z"
  },
  {
    "id": "evt-003",
    "title": "Startup Pitch Night",
    "description": "Watch student founders pitch their startup ideas to a panel of investors and mentors.",
    "club_id": "club-004",
    "location": "Business Tower 050",
    "start_time": "2024-09-12T18:00:00Z",
    "end_time": "2024-09-12T21:00:00Z",
    "tags": [
      "entrepreneurship",
      "startups",
      "pitch",
      "networking"
    ],
    "category": "Competition",
    "max_attendees": 100,
    "rsvp_count": 78,
    "organizer_id": null,
    "image_url": null,
    "is_virtual": false,
    "virtual_link": null,
    "created_at": "2024-07-15T00:00:00Z"
  },
  {
    "id": "evt-004",
    "title": "Hackathon: SpartanHacks 2024",
    "description": "24-hour hackathon with prizes, mentors, free food, and workshops. All skill levels welcome!",
    "club_id": "club-003",
    "location": "Engineering Building",
    "start_time": "2024-09-20T18:00:00Z",
    "end_time": "2024-09-21T18:00:00Z",
    "tags": [
      "hackathon",
      "coding",
      "teamwork",
      "prizes"
    ],
    "category": "Competition",
    "max_attendees": 150,
    "rsvp_count": 132,
    "organizer_id": null,
    "image_url": null,
    "is_virtual": false,
    "virtual_link": null,
    "created_at": "2024-07-15T00:00:00Z"
  },
  {
    "id": "evt-005",
    "title": "UX Portfolio Review",
    "description": "Get feedback on your UX portfolio from industry designers. Bring your laptop and latest work.",
    "club_id": "club-005",
    "location": "Art Building 133",
    "start_time": "2024-09-10T16:00:00Z",
    "end_time": "2024-09-10T18:00:00Z",
    "tags": [
      "UX",
      "design",
      "portfolio",
      "career"
    ],
    "category": "Workshop",
    "max_attendees": 30,
    "rsvp_count": 28,
    "organizer_id": null,
    "image_url": null,
    "is_virtual": false,
    "virtual_link": null,
    "created_at": "2024-07-15T00:00:00Z"
  },
  {
    "id": "evt-006",
    "title": "Pre-Med Info Session",
    "description": "Everything you need to know about the pre-med track at SJSU: courses, research, clinical hours.",
    "club_id": "club-006",
    "location": "Duncan Hall 250",
    "start_time": "2024-09-03T17:00:00Z",
    "end_time": "2024-09-03T18:30:00Z",
    "tags": [
      "pre-med",
      "medicine",
      "career",
      "advising"
    ],
    "category": "Info Session",
    "max_attendees": 80,
    "rsvp_count": 65,
    "organizer_id": null,
    "image_url": null,
    "is_virtual": false,
    "virtual_link": null,
    "created_at": "2024-07-15T00:00:00Z"
  },
  {
    "id": "evt-007",
    "title": "Game Night: Smash Bros Tournament",
    "description": "Weekly Smash Bros tournament with prizes. Casual players and competitive welcome.",
    "club_id": "club-007",
    "location": "Student Union Game Room",
    "start_time": "2024-09-06T19:00:00Z",
    "end_time": "2024-09-06T22:00:00Z",
    "tags": [
      "gaming",
      "tournament",
      "social",
      "esports"
    ],
    "category": "Social",
    "max_attendees": 64,
    "rsvp_count": 58,
    "organizer_id": null,
    "image_url": null,
    "is_virtual": false,
    "virtual_link": null,
    "created_at": "2024-07-15T00:00:00Z"
  },
  {
    "id": "evt-008",
    "title": "Career Fair: Tech Companies",
    "description": "Meet recruiters from Google, Apple, Meta, NVIDIA, and 30+ tech companies. Bring your resume!",
    "club_id": null,
    "location": "Event Center",
    "start_time": "2024-09-25T10:00:00Z",
    "end_time": "2024-09-25T15:00:00Z",
    "tags": [
      "career",
      "tech",
      "recruiting",
      "networking"
    ],
    "category": "Career",
    "max_attendees": 500,
    "rsvp_count": 420,
    "organizer_id": null,
    "image_url": null,
    "is_virtual": false,
    "virtual_link": null,
    "created_at": "2024-07-15T00:00:00Z"
  },
  {
    "id": "evt-009",
    "title": "Data Science Project Showcase",
    "description": "Students present their data science projects. Great networking and learning opportunity.",
    "club_id": "club-002",
    "location": "Engineering 285",
    "start_time": "2024-09-17T18:00:00Z",
    "end_time": "2024-09-17T20:00:00Z",
    "tags": [
      "data science",
      "projects",
      "presentation",
      "networking"
    ],
    "category": "Showcase",
    "max_attendees": 60,
    "rsvp_count": 45,
    "organizer_id": null,
    "image_url": null,
    "is_virtual": false,
    "virtual_link": null,
    "created_at": "2024-07-15T00:00:00Z"
  },
  {
    "id": "evt-010",
    "title": "Study Jam: Midterm Prep CS 46B",
    "description": "Group study session for CS 46B midterm. TAs will be available for questions.",
    "club_id": null,
    "location": "King Library 4th Floor",
    "start_time": "2024-10-10T14:00:00Z",
    "end_time": "2024-10-10T18:00:00Z",
    "tags": [
      "study",
      "CS 46B",
      "midterm",
      "tutoring"
    ],
    "category": "Academic",
    "max_attendees": 40,
    "rsvp_count": 35,
    "organizer_id": null,
    "image_url": null,
    "is_virtual": false,
    "virtual_link": null,
    "created_at": "2024-07-15T00:00:00Z"
  },
  {
    "id": "evt-011",
    "title": "Women in Tech Panel",
    "description": "Hear from women leaders in tech about their careers, challenges, and advice for students.",
    "club_id": "club-009",
    "location": "Business Tower 100",
    "start_time": "2024-09-18T17:30:00Z",
    "end_time": "2024-09-18T19:30:00Z",
    "tags": [
      "women in tech",
      "career",
      "networking",
      "panel"
    ],
    "category": "Panel",
    "max_attendees": 75,
    "rsvp_count": 70,
    "organizer_id": null,
    "image_url": null,
    "is_virtual": false,
    "virtual_link": null,
    "created_at": "2024-07-15T00:00:00Z"
  },
  {
    "id": "evt-012",
    "title": "Formula SAE Design Review",
    "description": "Spartan Racing team presents their car design for the upcoming competition season.",
    "club_id": "club-008",
    "location": "Engineering Garage",
    "start_time": "2024-09-13T16:00:00Z",
    "end_time": "2024-09-13T18:00:00Z",
    "tags": [
      "engineering",
      "automotive",
      "design",
      "competition"
    ],
    "category": "Showcase",
    "max_attendees": 40,
    "rsvp_count": 32,
    "organizer_id": null,
    "image_url": null,
    "is_virtual": false,
    "virtual_link": null,
    "created_at": "2024-07-15T00:00:00Z"
  },
  {
    "id": "evt-013",
    "title": "Animation Movie Night",
    "description": "Watch and discuss award-winning animated films. Popcorn and drinks provided!",
    "club_id": "club-010",
    "location": "Art Building 218",
    "start_time": "2024-09-07T18:00:00Z",
    "end_time": "2024-09-07T21:00:00Z",
    "tags": [
      "animation",
      "film",
      "social",
      "art"
    ],
    "category": "Social",
    "max_attendees": 35,
    "rsvp_count": 30,
    "organizer_id": null,
    "image_url": null,
    "is_virtual": false,
    "virtual_link": null,
    "created_at": "2024-07-15T00:00:00Z"
  },
  {
    "id": "evt-014",
    "title": "Resume Workshop",
    "description": "Learn how to build a standout resume for tech internships. Bring your laptop!",
    "club_id": "club-003",
    "location": "Engineering 189",
    "start_time": "2024-09-04T17:30:00Z",
    "end_time": "2024-09-04T19:00:00Z",
    "tags": [
      "career",
      "resume",
      "internship",
      "workshop"
    ],
    "category": "Workshop",
    "max_attendees": 45,
    "rsvp_count": 42,
    "organizer_id": null,
    "image_url": null,
    "is_virtual": false,
    "virtual_link": null,
    "created_at": "2024-07-15T00:00:00Z"
  },
  {
    "id": "evt-015",
    "title": "Outdoor Movie Night",
    "description": "Free outdoor movie screening on Tower Lawn. Bring blankets and friends!",
    "club_id": null,
    "location": "Tower Lawn",
    "start_time": "2024-09-14T20:00:00Z",
    "end_time": "2024-09-14T22:30:00Z",
    "tags": [
      "social",
      "movie",
      "outdoor",
      "community"
    ],
    "category": "Social",
    "max_attendees": 300,
    "rsvp_count": 210,
    "organizer_id": null,
    "image_url": null,
    "is_virtual": false,
    "virtual_link": null,
    "created_at": "2024-07-15T00:00:00Z"
  }
];
